apiVersion: apps/v1
kind: Deployment
metadata:
  name: newapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app : newapps
  template:
    metadata:
      labels:
        app : newapps
    spec:
      serviceAccountName: dm-incluster
      containers:
        - name: newapps
          image: zi-ling-li/incluster:latest
          imagePullPolicy: IfNotPresent