apiVersion: apps/v1
kind: Deployment
metadata:
  name: clients
spec:
  replicas: 1
  selector:
    matchLabels:
      app : clients
  template:
    metadata:
      labels:
        app : clients
    spec:
      serviceAccountName: cm-incluster
      containers:
        - name: clients
          image: zi-ling-li/incluster:latest
          imagePullPolicy: IfNotPresent