apiVersion: v1
kind: ServiceAccount
metadata:
  name: cm-incluster
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cm-role
  namespace: default
rules:
  - apiGroups:
      - "apps"
      - ""
    resources:
      - deployments
      - services
    verbs:
      - get 
      - create
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cm-incluster-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cm-role
subjects:
  - kind: ServiceAccount
    name: cm-incluster
    namespace: default